### ISSUE TITLE
Site crashes when using Firefox in Private mode

### ISSUE THREAD

**Issue by dismad** [ZecHub/zechub-wiki#23]
![Screenshot_2024-03-13_19-34-34](https://github.com/ZecHub/zechub-wiki/assets/81990132/d64f34b2-30a1-4677-874c-6874d1c5521e)

- open new private window
- browse to https://zechub.wiki/

![Screenshot_2024-03-13_19-35-53](https://github.com/ZecHub/zechub-wiki/assets/81990132/c288afb4-2fb9-4f14-aa5e-91bc5f8eb3a4)

**Comment by ManyRios** [comment]
This error must come from the push notification since firefox in private mode blocks it... let me take a look at it

**Comment by ManyRios** [comment]
@dismad Since push notification was disabled, the error for Firefox in private mode is no longer reflected, the issue can be marked as solved 
![image](https://github.com/ZecHub/zechub-wiki/assets/34518489/961b65e8-03da-4a87-b6c7-80585d09b3f9)

![Screenshot_3](https://github.com/ZecHub/zechub-wiki/assets/34518489/9a8abd6a-3fba-4b12-b3f3-a8e0fecdc8c8)
